FROM node:24-alpine

RUN apk update && \
    apk add --no-cache ffmpeg py3-pip && \
    pip3 install yt-dlp

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY . .

CMD ["node", "main.js"]
